### ISSUE TITLE
Wen NuGet

### ISSUE THREAD

**Issue by 0ptim** [defichaininfo/Jellyfish.NET#1]
Great Project!
Had the same idea some months ago but did not find the time to create such a library.
Glad someone made it. Will consider contributing in the future.

Will the library be available from the official [NuGet](https://www.nuget.org/) feed?

**Comment by defichaininfo** [comment]
Hi 0ptim, we're glad you like it! 
Yeah, actually, making a NuGet package out of it is the next step for this project.
Looking forward to your contribution as well!

**Comment by defichaininfo** [comment]
We wanted to let you know that a NuGet package is now officially released! :)
